[package]
name = "windowing"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[features]
# default = ["winit"] # deleteme!
# default = ["baseview"] # deleteme!

winit = ["dep:winit"]
baseview = ["dep:baseview", "dep:raw-window-handle", "dep:baseview-raw-window-handle" ]

[dependencies]
winit = { workspace = true, optional = true }
baseview = { workspace = true, optional = true}
peniko = { workspace = true }
slotmap = { workspace = true }
raw-window-handle = { workspace = true, optional = true }
baseview-raw-window-handle = { package = "raw-window-handle", version = "0.5.2", optional = true }
